name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas numpy scikit-learn xgboost matplotlib seaborn pytest-cov

      # Create logs directory
      - name: Create logs directory
        run: mkdir -p logs

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest tests/ --verbose --cov=src/ --cov-report=xml

      # Upload coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        if: success()